# Generated by Django 3.2.8 on 2022-06-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Імя')),
                ('number', models.BinaryField(verbose_name='номер')),
                ('time', models.TimeField(verbose_name='на яку годину')),
            ],
        ),
    ]
