# Generated by Django 3.2.8 on 2022-06-27 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiHome', '0003_alter_record_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='запис дати'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(verbose_name='запис годни'),
        ),
    ]
